### ISSUE TITLE
[FEAT] - More Icons Needed for Android

### ISSUE THREAD

**Issue by theamazing0** [thepurplebubble/cdn#1]
### What feature would you like to see?

The only icon currently included follows Apple's design for iOS only. The Android platform has much more possibilities of shapes for the icon and has support for user theming of icons.

The possibilities are described here: https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#add-to-your-app

**Comment by jaspermayone** [comment]
Feel free to take this if you want!

**Comment by jaspermayone** [comment]
Closing as we don't actually provide icons just a logo file.
